name: Node.js CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest 

    env:
      NODE_VERSION: 18 

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 

    - name: Set up Node.js
      uses: actions/setup-node@v3 
      with:
        node-version: ${{ env.NODE_VERSION }} 
        GH_TOKEN: ${{ secrets.API_KEY }}

    - name: Run your tests or other commands
      env:
        API_KEY: ${{ secrets.MY_SECRETS }}
      run: |
        echo "Using API_KEY: $API_KEY"
        # Run any other commands here that require the API_KEY
