name: Node.js CI

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

    env:
      API_KEY: ${{ secrets.MY_SECRETS }}   # Access the API_KEY from GitHub secrets
      NODE_VERSION: 18      

# Define the jobs that run in the workflow
jobs:
  build:
    runs-on: ubuntu-latest  # This defines the OS where the workflow runs

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # This checks out your code from the repository

    - name: Set up Node.js
      uses: actions/setup-node@v3  # This sets up Node.js on the runner
      with:
        node-version: ${{env.NODE_VERSION}}
        GH_TOKEN: ${{secrets.API_KEY}} # Specify the Node.js version you want to use

