name: First_GITHUB ACTION CODE

on:
  pull_request:
    branches:
      - main
  push:
    branches:
     - main
env:
  NODE_VERSION: 18
  # Secrets_Value: ${{secrets.MY_SECRETS}}

jobs:
  My_build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Use Node version
        uses: actions/setup-node@v3
        with:
           node-version: ${{ env.NODE_VERSION }}
